### ISSUE TITLE
Avaliação da Proposta de Trabalho

### ISSUE THREAD

**Issue by santos-fernando** [ruanfelipe77/Trabalho-de-Busca-em-Largura---INC#1]
EQUIPE
Ok (individual)
PROBLEMA
Ok: jogo da velha
DATASET 
Ok, não se aplica.
TÉCNICA
INCORRETO. A técnica apropriada para o Jogo da Velha é a busca competitiva (minimax).
O aluno deve propor alguma “variação” do jogo da velha, pois o jogo da velha clássico (3x3) foi utilizado como exemplo durante a aula e então a sua resposta está pronta nos slides. Sugestão de variações para o jogo da velha:
- aumentar o tamanho do tabuleiro: 4x4, 5x5, etc
- jogo da velha 3d (exemplo: https://www.mathsisfun.com/games/foursight-3d-tic-tac-toe.html)
Esta variação será fundamental para obter boa avaliação/nota no trabalho.
 
OBSERVAÇÕES
A equipe tem prazo até dia 14/08 para providenciar os ajustes acima descritos e obter novo feedback do professor.

**Comment by ruanfelipe77** [comment]
Atualizei o GIT professor. Vi a mensagem sobre o trabalho de árvores em
aberto. Posso enviar ainda ao menos pela presença? Acho que a atividade já
fechou no moodle.

Em qui., 13 de ago. de 2020 às 17:30, Fernando Santos <
notifications@github.com> escreveu:

**Comment by santos-fernando** [comment]
Tudo ok nesta etapa.
